### ISSUE TITLE
Initial revision is not created after the first edition in a copied content

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.versioningbehavior#12]
After copying a content and edit that copy, the initial revision is not created.

Copy of archetype content  edited once:

![selecao_007](https://cloud.githubusercontent.com/assets/8203476/7400390/fde155d6-ee92-11e4-8de5-0ebd771bcfa9.png)

Copy of dexterity content (using plone.app.versioningbehavior)  edited once:

![selecao_008](https://cloud.githubusercontent.com/assets/8203476/7400438/528b7d14-ee93-11e4-8854-6c212443ebc0.png)

This is bad because we can not compare the initial revision with the first modification.

**Comment by rafaelbco** [comment]
Here's what I found out trying to fix this.

This is what happens when a Dexterity item is pasted:

* The `.subscriber.create_version_on_save` event handler is called. This function creates the 
  initial version of the pasted item. 

* `Products.CMFEditions` assign a `history_id` to the item. A CMF tool called 
  `portal_historyidhandler` handles the creation and assignment of this `history_id`. 
  It's class is `Products.CMFEditions.historyidhandlertool.HistoryIdHandlerTool` and it 
  stores the `history_id` in an attribute of the item called `cmf_uid`.

* Another relevant event handler is called: 
  `Products.CMFUid.UniqueIdAnnotationTool.handleUidAnnotationEvent`. This function calls
  `Products.CMFUid.UniqueIdHandlerTool.unregister` which removes the `cmf_uid` attribute.

* Without the `version_id` (which is actually stored as the `cmf_uid` attribute) the version is 
  lost.

So, when the first edit occurs in the pasted object, we don't have an initial version and cannot
keep track of the changes. On the second edit versioning occurs normally.

Why does it works for Archetypes?

When an item is pasted the initial version is not created. It's created right before the first
edit is saved. Although this approach works I don't believe it is correct, because the behavior
of a pasted item is different from a new one: the pasted item does not have an initial
version.

Unfortunately I can't see an obvious way to fix this. Any thoughts ?

**Comment by idgserpro** [comment]
@pbauer @mauritsvanrees any thoughts on this issue and this difference between Archetypes and Dexterity?

**Comment by ale-rt** [comment]
Note in this commit  https://github.com/plone/plone.app.versioningbehavior/commit/c0d7401894797a5c0565c5e5ea305c049b92ebdc
the event handler registered for IObjectAddedEvent was changed from `create_initial_version_after_adding` to `create_version_on_save`

**Comment by ale-rt** [comment]
If I got that right this is an AT only issue.
We do not support AT anymore, so I will close this issue.
Feel free to reopen if I am wrong.

**Comment by idgserpro** [comment]
@ale-rt  It's actually the opposite. It works on Archetype and it doesn't work on dexterity. This problem still occurs in Plone 5.2. So please reopen.
