### ISSUE TITLE
Switching to manual versioning has no effects

### ISSUE THREAD

**Issue by juh2** [plone/plone.app.versioningbehavior#13]
When I switch to manual versioning in @@types-controlpanel this has no effect. The GUI of the content type does not change. There should be a radio button to say "store a new version" or something like this.

**Comment by jone** [comment]
This works slightly different than with Archetypes:
The ``IVersionable`` behavior provides a normal textline field: https://github.com/plone/plone.app.versioningbehavior/blob/master/plone/app/versioningbehavior/behaviors.py#L17

As far as I remember it was not that easy to do this with a viewlet, as it's done for Archetypes, because it caused troubles in combination with z3cform / dexterity mechanisms. Therefore it is a simple field.

Did you enable the ``IVersionable`` behavior for your content type?
Is the field probably in a wrong schemata?

**Comment by juh2** [comment]
I use plone 5 beta, no custom content types.

**Comment by jone** [comment]
As far as I see not all types have the ``IVersionable`` behavior: https://github.com/plone/plone.app.contenttypes/search?utf8=%E2%9C%93&q=IVersionable
With which type do you experience this behavior?

**Comment by juh2** [comment]
A Page

**Comment by vangheem** [comment]
maybe plone.app.versioningbehavior doesn't have a manual versioning mode? Maybe that setting is an artifact of archetypes?

**Comment by vangheem** [comment]
Nevermind, versioning is done the same whether it is archetypes or dexterity. I'll look into getting manual versioning working.

**Comment by vangheem** [comment]
The way versioning works now is a bit different. There is no "create new version" checkbox anymore. To create a new version in manual mode, you must provide a change note. I added a better description to that field.
